### ISSUE TITLE
Permission denied on sqlite database when use TLS

### ISSUE THREAD

**Issue by slefol** [crowdsecurity/helm-charts#114]
Hi,
 I have noticed a issue with the dashboard when tls.enabled is set to true.

##### Environment
Helm chart : crowdsec
Helm chart version : 0.9.9

```
$ helm install \
    crowdsec crowdsec/crowdsec \
    --create-namespace \
    --namespace crowdsec \
    -f crowdsec-values.yaml
```

crowdsec-values.yaml:
```yaml
container_runtime: containerd
tls:
  enabled: true
  bouncer:
    reflector:
      namespaces: ["traefik"]
agent:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    # When testing, allow bans on private networks
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
  persistentVolume:
    config:
      enabled: false
lapi:
  dashboard:
    enabled: true
    ingress:
      host: dashboard.local
      enabled: true
  persistentVolume:
    config:
      enabled: false
  env:
    # For an internal test, disable the Online API
    - name: DISABLE_ONLINE_API
      value: "true"
```

##### Issue
In dashboard > Browse data > Cdrodsec > Alerts
[SQLITE_CANTOPEN] Unable to open the database file (unable to open database file)

##### Investigation
In Admin Settings > Databases > Crowdsec > Save changes
/metabase-data/crowdsec.db (Permission denied)

The dashboard is launched with the metabase user who does not have rights to the database file.
```
$ kubectl -n crowdsec exec -it crowdsec-lapi-7c79988958-q89ln -c dashboard -- sh
/ # ps faux
PID   USER     TIME  COMMAND
    1 metabase  1:30 java -XX:+IgnoreUnrecognizedVMOptions -Dfile.encoding=UTF-8 -Dlogfile.path=target/log -XX:+CrashOnOutOfMemoryError -server -jar /app/metabase.jar

/ # readlink /metabase-data/crowdsec.db
/var/lib/crowdsec/data/crowdsec.db

/ # ls -lh /var/lib/crowdsec/data/crowdsec.db
-rw-r-----    1 root     root       84.0K Oct 13 07:19 /var/lib/crowdsec/data/crowdsec.db
```

Change group ownership of the database file fixes the issue
```
/ # chown :metabase /var/lib/crowdsec/data/crowdsec.db
```

**Comment by slefol** [comment]
Hi,
I installedHelm chart version : 0.11.0 and the issue is still present.
Can you please look into this issue ?

**Comment by LaurenceJJones** [comment]
> Hi, I installedHelm chart version : 0.11.0 and the issue is still present. Can you please look into this issue ?

Hey 👋🏻 

I dont think it has anything to do with TLS. By default the database is owned by `root:root` and the permissions are updating each time, could you try defining in the `lapi` environment a `GID` property of `2000` as that is the metabase group id from within the container.

https://github.com/crowdsecurity/helm-charts/blob/6bd1d202fa705775d928a1226bcc98c38ad6288d/charts/crowdsec/values.yaml#L145-L159

https://github.com/crowdsecurity/crowdsec/blob/c4bfdf19914a88671663f8caae5a5ea849c1b3a6/docker/docker_start.sh#L334-L341

```
/ # cat /etc/group
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
sys:x:3:root,bin,adm
adm:x:4:root,adm,daemon
tty:x:5:
disk:x:6:root,adm
lp:x:7:lp
mem:x:8:
kmem:x:9:
wheel:x:10:root
floppy:x:11:root
mail:x:12:mail
news:x:13:news
uucp:x:14:uucp
man:x:15:man
cron:x:16:cron
console:x:17:
audio:x:18:
cdrom:x:19:
dialout:x:20:root
ftp:x:21:
sshd:x:22:
input:x:23:
at:x:25:at
tape:x:26:root
video:x:27:root
netdev:x:28:
readproc:x:30:
squid:x:31:squid
xfs:x:33:xfs
kvm:x:34:kvm
games:x:35:
shadow:x:42:
cdrw:x:80:
www-data:x:82:
usb:x:85:
vpopmail:x:89:
users:x:100:games
ntp:x:123:
nofiles:x:200:
smmsp:x:209:smmsp
locate:x:245:
abuild:x:300:
utmp:x:406:
ping:x:999:
nogroup:x:65533:
nobody:x:65534:
metabase:x:2000:metabase
```

**Comment by slefol** [comment]
@LaurenceJJones Thank you for your interest in my request.

I defined in the lapi environment a GID property of 2000 but I get this error :
ComparisonError: error calculating structured merge diff: error building typed value from config resource: .spec.template.spec.containers[name="crowdsec-lapi"].env: duplicate entries for key [name="GID"]
(helm chart deployed by ArgoCD).

Indeed, we can see that variable is already defined in the template
https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/lapi-deployment.yaml#L87-L90

**Comment by LaurenceJJones** [comment]
Can you share your full values.yaml please?

**Comment by LaurenceJJones** [comment]
Because if you using the official metabase image, it should use the same MGID

```
          - name: MGID
            value: "1000"
```

**Comment by slefol** [comment]
my values.yaml :
```yaml
  container_runtime: containerd
  tls:
    enabled: true
    bouncer:
      reflector:
        namespaces: ["traefik"]
  agent:
    # Specify each pod whose logs we want to process
    acquisition:
      # The namespace where the pod is located
      - namespace: traefik
        # The pod name
        podName: traefik-*
        # as in crowdsec configuration, we need to specify the program name to find a matching parser
        program: traefik
    # Those are ENV variables
    env:
      - name: PARSERS
        value: "crowdsecurity/cri-logs"
      - name: COLLECTIONS
        value: "crowdsecurity/traefik"
      - name: DISABLE_PARSERS
        value: "crowdsecurity/whitelists"
    persistentVolume:
      config:
        enabled: false
  lapi:
    dashboard:
      enabled: true
      ingress:
        host: dashboard.local
        enabled: false
    persistentVolume:
      config:
        enabled: false
    env:
      # If it's a test, we don't want to share signals with CrowdSec so disable the Online API.
      - name: DISABLE_ONLINE_API
        value: "true"
      - name: GID
        value: "2000"
```
