### ISSUE TITLE
[FEATURE] Provide Agents username and password via (Sealed)Secret

### ISSUE THREAD

**Issue by teceP** [crowdsecurity/helm-charts#116]
I want to specify Agents username and password via a provided SealedSecret.

Instead of automatically creating this Secret automatically https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/secrets.yaml ,  I want to do something like this:

```yaml
    env:
      - name: AGENT_USERNAME
        valueFrom:
          secretKeyRef:
            name: agent-credentials-secret-envs
            key: username
      - name: AGENT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: agent-credentials-secret-envs
            key: password
```
(this doesnt work, since the AGENT_USERNAME and AGENT_PASSWORD are provided two times: by me and be the Secret i linked above)

or something like
```yaml
secretName: agent-credentials-secret-envs
```
where agent-credentials-secret-envs contains keys "username" and "password.

I do not want to provide a Base64 password, since it is easy to decode it into a plain password.
