### ISSUE TITLE
Issues reading nginx logs

### ISSUE THREAD

**Issue by marijusGood** [crowdsecurity/helm-charts#174]
Hi team,

I seem to have the same problem as described before where none of my logs get parsed. I am deploying everything within a k8s cluster. The output of my **cscli metrics**

```
╭──────────────────────────────────────────────────────────────┬────────────┬──────────────┬────────────────┬────────────────────────┬───────────────────╮
│                            Source                            │ Lines read │ Lines parsed │ Lines unparsed │ Lines poured to bucket │ Lines whitelisted │
├──────────────────────────────────────────────────────────────┼────────────┼──────────────┼────────────────┼────────────────────────┼───────────────────┤
│ file:/var/log/containers/nginx-ingress-microk8s-controller-l │ 1          │ -            │ 1              │ -                      │ -                 │
│ dlp5_ingress_nginx-ingress-microk8s-ace27de928e788d77337c3c2 │            │              │                │                        │                   │
│ a8a60698f9b3a42109a834fb0d88a891eb3f04aa.log                 │            │              │                │                        │                   │
╰──────────────────────────────────────────────────────────────┴────────────┴──────────────┴────────────────┴────────────────────────┴───────────────────╯

Parser Metrics:
╭────────────────────────────────┬──────┬────────┬──────────╮
│             Parsers            │ Hits │ Parsed │ Unparsed │
├────────────────────────────────┼──────┼────────┼──────────┤
│ child-crowdsecurity/nginx-logs │ 3.00k    │ -      │ 3.00k        │
│ crowdsecurity/nginx-logs       │ 3.00k    │ -      │ 3.00k        │
│ crowdsecurity/non-syslog       │ 3.00k    │ 3.00k      │ -        │
╰────────────────────────────────┴──────┴────────┴──────────╯
```
when my nginx logs look like this:
```
83.150.2.35 - - [28/Jun/2024:14:15:08 +0000] "GET /selfTestPci586.d HTTP/2.0" 200 53 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 32 0.204 [es-dev-es-dev-443] [] 10.1.187.164:8443 53 0.203 200 d77633989c1e405f9321cfa84f545197
83.150.2.35 - - [28/Jun/2024:14:15:08 +0000] "GET /selfTestPci586.d HTTP/2.0" 200 53 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 32 0.183 [es-dev-es-dev-443] [] 10.1.187.164:8443 53 0.182 200 733fed93485463aa28918026e93ced5b
```

and my values.yaml is:
```
agent:
  acquisition:
    - namespace: ingress
      # The pod name
      podName: nginx-ingress-microk8s-controller-*
      program: nginx

  # Those are ENV variables
  env:
  - name: DISABLE_ONLINE_API
    value: "true"
  - name: COLLECTIONS
    value: "crowdsecurity/nginx"
lapi:
  env:
    - name: DISABLE_ONLINE_API
      value: "true"
```

I tried setting container_runtime to cri, docker, container and ngnix with no avail. I also tried to add:
```
- name: PARSERS
    value: "crowdsecurity/cri-logs"
```

but it did not help. Help regarding this topic would be very appreciated, thanks!

**Comment by LaurenceJJones** [comment]
Hmmm so I tested the logs within a debugger and its parses

![image](https://github.com/crowdsecurity/helm-charts/assets/23139695/a21ad30c-549b-426c-a77d-4c0d18137bb2)

Can you get the log lines directly from the file from what CrowdSec see's

**Comment by marijusGood** [comment]
Sure thing!

So the file that it tries to parse is `/var/log/containers/nginx-in
gress-microk8s-controller-ldlp5_ingress_nginx-ingress-microk8s-ace27de928e788d77337c3c2a8a60698f9b3a42109a834fb0d88a891eb3f04aa.log`

I have attached a file that contains a part of the lines that are in the mentioned file [ngnix.log](https://github.com/user-attachments/files/16100960/ngnix.log)

let me know if you need more information and thanks for the fast reply!

**Comment by LaurenceJJones** [comment]
> Sure thing!
> 
> So the file that it tries to parse is `/var/log/containers/nginx-in
> gress-microk8s-controller-ldlp5_ingress_nginx-ingress-microk8s-ace27de928e788d77337c3c2a8a60698f9b3a42109a834fb0d88a891eb3f04aa.log`
> 
> I have attached a file that contains a part of the lines that are in the mentioned file [ngnix.log](https://github.com/user-attachments/files/16100960/ngnix.log)
> 
> let me know if you need more information and thanks for the fast reply!

So looking at the logs that is cri format, so the container_runtime should be `containerd` which sets the correct s00 and then the program should still be `nginx`

**Comment by marijusGood** [comment]
Thank you for the help, it worked!

I have a small question regarding email notifications. In my helm values I have added:
```
config:
  notifications:
    email.yaml: |
      type: email
      name: email_default
      log_level: info
      smtp_host: XXXXXXXX
      smtp_username: XXXXXXXX
      smtp_password: XXXXXXXX
      smtp_port: 587
      auth_type: login
      sender_name: "CrowdSec"
      sender_email: XXXXXXXX
      email_subject: "CrowdSec Notification"
      receiver_emails:
        - XXXXXXXX
        - XXXXXXXX
    slack.yaml: ""
    http.yaml: ""
    splunk.yaml: ""
    ```
    
    and running `kubectl get configmap -n crowdsec crowdsec-notifications -o yaml` I see:
    ```
apiVersion: v1
data:
  email.yaml: |
    type: email
    name: email_default
    log_level: info
    smtp_host: XXXXXXXX
    smtp_username: XXXXXXXX
    smtp_password: XXXXXXXX
    smtp_port: 587
    auth_type: login
    sender_name: "CrowdSec"
    sender_email: XXXXXXXX
    email_subject: "CrowdSec Notification"
    receiver_emails:
      - XXXXXXXX
      - XXXXXXXX
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: crowdsec
    meta.helm.sh/release-namespace: crowdsec
  creationTimestamp: "2024-07-05T14:03:50Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: crowdsec-notifications
  namespace: crowdsec
  resourceVersion: "23367747"
  uid: 936867d2-3036-4d59-addf-97d9a29f0a37
```

but if I exec into the pod and do `cat /etc/crowdsec/notifications/email.yaml` the values are not there and the email is not sent
and in `/etc/crowdsec/profiles.yaml` the information also has not changed

Thanks for the help
