### ISSUE TITLE
Add additionalLabels to serviceMonitors

### ISSUE THREAD

**Issue by urbaman** [crowdsecurity/helm-charts#177]
Please add an additionalLabels: tag to serviceMonitors, so people is able to add labels scraped by prometheus with prometheus.

Example:

```yaml
additionalLabels:
  release: kube-prometheus-stack
```

**Comment by LaurenceJJones** [comment]
And this cannot be achieved via these labels?

https://github.com/crowdsecurity/helm-charts/blob/6bd1d202fa705775d928a1226bcc98c38ad6288d/charts/crowdsec/values.yaml#L327

https://github.com/crowdsecurity/helm-charts/blob/6bd1d202fa705775d928a1226bcc98c38ad6288d/charts/crowdsec/values.yaml#L180

**Comment by urbaman** [comment]
No, they should be added in the servicemonitor templates (the one you pointed to for example) in the metadata section, something like this:

Template:

```yaml
metadata:
  name: {{ .Release.Name }}-agent-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
    {{- if .Values.agent.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.agent.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
```

values.yaml:

```yaml
metrics:
    enabled: false
    # -- Creates a ServiceMonitor so Prometheus will monitor this service
    # -- Prometheus needs to be configured to watch on all namespaces for ServiceMonitors
    # -- See the documentation: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape
    # -- See also: https://github.com/prometheus-community/helm-charts/issues/106#issuecomment-700847774
    serviceMonitor:
      enabled: false
      additionalLabels: {}
```


For both serviceMonitors.
