### ISSUE TITLE
Helm installed failed: unexpected EOF

### ISSUE THREAD

**Issue by onedr0p** [crowdsecurity/helm-charts#18]
I was trying to loosely follow this guide: https://crowdsec.net/blog/kubernetes-crowdsec-integration/

Trying to install 0.2.0

Helm values:

```yaml
    lapi:
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
    agent:
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
        - name: COLLECTIONS
          value: "crowdsecurity/nginx"
      acquisition:
        - namespace: networking
          podName: ingress-nginx-controller-*
          program: nginx
```

Error:

```
Helm install failed: parse error at (crowdsec/templates/lapi-deployment.yaml:108): unexpected EOF
```
