### ISSUE TITLE
`securityContext` Option Needed to Access `/var/log` when SELinux is Enabled

### ISSUE THREAD

**Issue by ImranR98** [crowdsecurity/helm-charts#190]
To read Traefik logs, CrowdSec needs access to the `/var/log/containers` directory, but this is inaccessible if the host has SELinux (like on Fedora).

I found ([source](https://itnext.io/minimally-privileged-containers-in-openshift-an-example-using-a-logging-agent-872e21fdce86)) that the solution (without disabling SELinux) is to add this option to the pod spec:
```yaml
securityContext:
  seLinuxOptions:
    type: container_logreader_t
``` 

I assume this can't be added to the Helm chart by default (would probably error out on non-SELinux systems but I haven't checked), but it should still be possible to set this in `values.yaml` but doesn't appear to be. Could this option be added?

Note: I'm grabbing Traefik logs by adding this to `values.yaml` (maybe there's an alternative?):
```yaml
agent:
  acquisition:
    - namespace: production
      podName: traefik-*
      program: traefik
```
