### ISSUE TITLE
Bug: auto registration not working for appsec

### ISSUE THREAD

**Issue by TimP4w** [crowdsecurity/helm-charts#203]
Not sure if it's a missconfiguration or an actual bug, however appsec autoregistration fails all the time and i have to manually validate it via cscli.

The issue is that being a deployment, every time a new pod is created it needs to be revalidated manually. Is this the desired behaviour or a bug?


This is the log I get
```

│ time="2024-11-24T16:55:04Z" level=fatal msg="unable to start crowdsec routines: authenticate watcher (security-crowdsec-appsec-b8ff487bd-kjl4z): API error: machine security-crowdsec-appsec-b8ff487bd-kjl4z not validated"        
```

My `values.yaml`

```
    container_runtime: containerd
    agent:
      acquisition:
        - namespace: network
          podName: traefik-*
          program: traefik
          poll_without_inotify: true
        - namespace: authentik
          podName: authentik-*
          program: authentik
          poll_without_inotify: true
        - namespace: homeassistant
          podName: homeassistant-*
          program: home-assistant
          poll_without_inotify: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            app.kubernetes.io/component: monitoring
      env:
        - name: PARSERS
          value: "crowdsecurity/cri-logs crowdsecurity/whitelists"
        - name: COLLECTIONS
          value: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/home-assistant firix/authentik"

    lapi:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            app.kubernetes.io/component: monitoring
      env:
        - name: ENROLL_KEY
          value: "<enroll key>"
        - name: ENROLL_INSTANCE_NAME
          value: "..."
        - name: ENROLL_TAGS
          value: "..."
        - name: BOUNCER_KEY_traefik
          value: "..."

    appsec:
      enabled: true
      acquisitions:
        - source: appsec
          listen_addr: "0.0.0.0:7422"
          path: /
          appsec_config: crowdsecurity/appsec-default
          labels:
            type: appsec
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
        - name: APPSEC_CONFIGS
          value: "crowdsecurity/appsec-default"

```

I can see that the secret  `crowdsec-lapi-secrets` exists and it's attached to the pod, and the `wait-for-lapi-and-register` job succeeds and registers appsec with the local LAPI

```
level=info msg="Successfully registered to Local API (LAPI)"                                                                                                                                                                                                                                                           
level=info msg="Local API credentials written to '/etc/crowdsec/local_api_credentials.yaml'"                                                                                                                                                                                                                           
level=warning msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."   
```

However `cscli machine list` shows it as not validated

```
security-crowdsec-lapi-69668bb5db-6cngc:/# cscli machine list
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                                              IP Address   Last Update           Status  Version                 OS                            Auth Type  Last Heartbeat
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ...
 security-crowdsec-appsec-b8ff487bd-kjl4z          10.42.2.30   2024-11-24T16:54:59Z  🚫                              ?                             password   ⚠️ -
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by blotus** [comment]
Hello,

This is actually a documentation issue :(

You need to add the following to your values (assuming your cluster is using the 10.0.0.0/8 IP range):
```
lapi:
  config.yaml.local: |
    api:
      server:
        auto_registration:
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges:
            - "10.0.0.8/8"
```
You can find the documentation for the auto validation feature [here](https://docs.crowdsec.net/u/user_guides/machines_mgmt/#machine-auto-validation)

When this config is set, the appsec will be able to register automatically to LAPI (you might need to delete the appsec pod after applying the change to force k8s to deploy a new version of the pod with the proper env variables)

**Comment by TimP4w** [comment]
I even saw this here https://github.com/crowdsecurity/helm-charts/pull/189/files#diff-46edd849e7dd696fb564f53733767c38e644bb97db91ad180254b66f4031248dR98 but thought it wasn't needed anymore as it wasn't in the README anymore... 

Thanks a lot!

For future reference, if someone stumbles across this issue in the future AND uses FluxCD's HelmRelease, the variable needs to be escaped with an extra `$`

```
lapi:
  config.yaml.local: |
    api:
      server:
        auto_registration:
          enabled: true
          token: "$${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges:
            - "10.0.0.8/8"
```
