### ISSUE TITLE
Appsec unable to register when using tls

### ISSUE THREAD

**Issue by pfaelzerchen** [crowdsecurity/helm-charts#204]
When trying to enable AppSec the `wait-for-lapi-and-register` container fails with the following log entry

```
level=fatal msg="api client register: api register (http://crowdsec-service.crowdsec:8080/) http 400 Bad Request: API error: http code 400, response: Client sent an HTTP request to an HTTPS server.\n"
```

I am using the tls configuration:

```yaml
        tls:
          enabled: true
          bouncer:
            reflector:
              namespaces: ["traefik"]
```

My AppSec values are:

```yaml
appsec:
  enable: true
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs crowdsecurity/appsec-generic-rules"
    - name: APPSEC_CONFIGS
      value: "crowdsecurity/appsec-default crowdsecurity/crs"

  strategy:
    type: Recreate

  metrics:
    enable: true
    serviceMonitor:
      enable: true
```

I did not see any tls-options in the default values.yaml. Probably tls activation is missing for the appsec deployment?
