### ISSUE TITLE
Duplicate key "command" for crowdsec-agent container in helm chart 0.16.0

### ISSUE THREAD

**Issue by Eyeless77** [crowdsecurity/helm-charts#224]
I use Flux CD to manage my crowdsec helm release. When I use chart version 0.16.0 I get an error:

`crowdsec with chart crowdsec@0.16.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 118: mapping key "command" already defined at line 64`

My values are the following:
```
...
agent:
  acquisition:
    - namespace: "traefik"
      podName: "traefik-*"
      program: "traefik"
      poll_without_inotify: true
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 150m
      memory: 100Mi
  persistence:
    config:
      enabled: true
      accessModes:
        - ReadWriteMany
      storageClassName: "freenas-nfs-csi"
      size: 100Mi
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs crowdsecurity/traefik-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
...
```

I tried to comment out different parts of my values and figured out that removing `persistense` section fixes that issue. With the same values I can successfully install crowdsec with chart version 0.15.0.

I checked diff between charts and I guess [here](https://github.com/crowdsecurity/helm-charts/compare/crowdsec-0.15.0...crowdsec-0.16.0#diff-f91a5fac6853bded4a8af63be0e94912fa27a31a2f31d9c4f614a8f70a428b24R101-R103) is the problem.

When `.Values.tls.enabled` is false and `.Values.agent.persistentVolume.config.enabled` is true (as I use in my setup), we've got duplicate `command` for agent container.
