### ISSUE TITLE
Agents CrashLoopBackOff with 0.16.0 ("machine not validated"), but work with 0.15.0

### ISSUE THREAD

**Issue by mossroy** [crowdsecurity/helm-charts#228]
Steps to reproduce:

Deploy the crowdsec helm chart with command-line like:

`helm upgrade --install crowdsec-tests crowdsec/crowdsec -f values-crowdsec-tests.yaml -n crowdsec-tests --version 0.16.0`

values-crowdsec-tests.yaml having this content (I replaced the enroll_key):
```
container_runtime: containerd

agent:
  acquisition:
    - namespace: kube-system
      podName: traefik-*
      program: traefik
  env:
    - name: TZ
      value: "Europe/Paris"
lapi:
  env:
    - name: TZ
      value: "Europe/Paris"
    - name: ENROLL_KEY
      value: "xxx"
    - name: ENROLL_INSTANCE_NAME
      value: "tests"
    - name: ENROLL_TAGS
      value: "tests"
```
All crowdsec-tests-agent-* pods of the cluster end up in CrashLoopBackOff state. Their main container always crashes with this log line:
```
crowdsec-agent time="2025-01-12T15:56:48+01:00" level=fatal msg="unable to start crowdsec routines: authenticate watcher (crowdsec-tests-agent-g6mpd): API error: machine crowdsec-tests-agent-g6mpd not validated"
```
The lapi logs shows corresponding HTTP 401:
`time="2025-01-12T15:59:34+01:00" level=info msg="10.42.3.139 - [Sun, 12 Jan 2025 15:59:34 CET] \"POST /v1/watchers/login HTTP/1.1 401 925.301µs \"crowdsec/v1.6.4-523164f6-docker\"`

Although the initContainer had completed successfully with this log:
```
waiting for lapi to start
level=info msg="Successfully registered to Local API (LAPI)"
level=info msg="Local API credentials written to '/etc/crowdsec/local_api_credentials.yaml'"
level=warning msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
```
which resulted in the following lapi HTTP 201 log:
`time="2025-01-12T15:57:57+01:00" level=info msg="10.42.3.139 - [Sun, 12 Jan 2025 15:57:57 CET] \"POST /v1/watchers HTTP/1.1 201 98.277103ms \"crowdsec/v1.6.4-523164f6-docker\" \""
`

But if I switch to v0.15.0, with:
`helm upgrade --install crowdsec-tests crowdsec/crowdsec -f values-crowdsec-tests.yaml -n crowdsec-tests --version 0.15.0`
then the agents start with no issue

NB: tested on k3s v1.31.4+k3s1, with helm 3.16.4 and kubectl v1.31.4+k3s1

**Comment by srkoster** [comment]
hi @mossroy thanks for reporting this.

Version 0.16.0 changes the default authentication option between the agent and LAPI to auto_registration (see #209). 
However, you have to adapt your `values.yaml` to make it work. If you add the code below and adapt the `allowed_ranges` to your needs, it will

```
config:
  config.yaml.local: |
    api:
      server:
        auto_registration: # Activate if not using TLS for authentication or when using Appsec
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges: # Make sure to adapt to the IP ranges used by your cluster
            - "127.0.0.1/32"
            - "192.168.0.0/16"
            - "10.0.0.0/8"
            - "172.16.0.0/12"
```

@he2ss this configuration is currently commented out in the `values.yaml`. Should we uncomment it?
