### ISSUE TITLE
Tolerations as a list not a object

### ISSUE THREAD

**Issue by onedr0p** [crowdsecurity/helm-charts#23]
Hi 👋🏼 I would like to apply tolerations like this:

```yaml
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```

Most charts I see tolerations support via `[]` not `{}` and `[]` is the official way: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by rlex** [comment]
should work, tolerations are generated like that: 
```
{{- toYaml . | nindent 8 }}
```
So you can pass freeform yaml to that variable

**Comment by onedr0p** [comment]
Ah right, I am getting a error though... 

```
reconciliation failed: Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 84: mapping key "tolerations" already defined at line 24
```

Helm values:

```yaml
    container_runtime: containerd
    lapi:
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
      persistentVolume:
        data:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ceph-block
          size: 1Gi
        config:
          enabled: true
          accessModes:
            - ReadWriteOnce
          storageClassName: ceph-block
          size: 100Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 150m
          memory: 100Mi
    agent:
      env:
        - name: DISABLE_ONLINE_API
          value: "true"
        - name: COLLECTIONS
          value: "crowdsecurity/nginx"
      acquisition:
        - namespace: networking
          podName: ingress-nginx-controller-*
          program: nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
```

**Comment by rlex** [comment]
That's interesting. I checked on my install and it applies correctly (diff no-tolerations vs tolerations)
```
        - name: crowdsec-config
          persistentVolumeClaim:
            claimName: crowdsec-config-pvc
+       tolerations:
+         - effect: NoSchedule
+           operator: Exists
+         - effect: NoExecute
+           operator: Exists
        nodeSelector:
          node-role.kubernetes.io/worker: "true"
```

Tolerations are also properly applied to workloads, both for lapi and agents.

Here is my full config (in helmfile format)
```
repositories:
  - name: crowdsec
    url: https://crowdsecurity.github.io/helm-charts
bases:
  - ../../environments/environments.yaml
---
releases:
  - name: crowdsec
    namespace: crowdsec
    kubeContext: {{ .Environment.Values.global_kubecontext }}
    createNamespace: true
    chart: crowdsec/crowdsec
    values:
      - container_runtime: containerd
      - agent:
          acquisition:
            - namespace: ingress-nginx
              podName: ingress-nginx-controller-*
              program: nginx
          env:
            - name: PARSERS
              value: "crowdsecurity/cri-logs"
            - name: DISABLE_ONLINE_API
              value: "true"
            # As we are running Nginx, we want to install the Nginx collection
            - name: COLLECTIONS
              value: "crowdsecurity/nginx"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          nodeSelector:
            node-role.kubernetes.io/worker: "true"
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
      - lapi:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          dashboard:
            enabled: true
            image:
              tag: "v0.41.5"
            ingress:
              enabled: true
              ingressClassName: nginx
              host: crowdsec.{{ .Environment.Values.global_ingress_basedomain }}
          persistentVolume:
            data:
              storageClassName: local-path
              size: 1Gi
            config:
              storageClassName: local-path
              size: 100Mi
          nodeSelector:
            node-role.kubernetes.io/worker: "true"
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
```
