### ISSUE TITLE
agents re-register when restarting daemonset

### ISSUE THREAD

**Issue by brightdroid** [crowdsecurity/helm-charts#230]
When I/anything restarts my agent damonset, the agents try to re-register with a new name (pod name).

Is this supposed to work like this? As the list of machines in cscli grow which is wrong as I only have 3 nodes/pods.

Thank you

**Comment by srkoster** [comment]
That's expected behavior with TLS authentication or using an auto registration token.
You can tidy up stale entries yourself, or use the [flush settings](https://docs.crowdsec.net/docs/next/configuration/crowdsec_configuration/#flush).

```
config:
  config.yaml.local: |
    db_config:
      flush:
        bouncers_autodelete:
          cert: 60m
          api_key: 60m
        agents_autodelete:
          cert: 60m
          login_password: 60m
        ## Flush both cert and login password if not logged in for 60 minutes or more
```
