### ISSUE TITLE
Invalid YAML generated when appsec is enabled and podAnnotations are configured

### ISSUE THREAD

**Issue by krezovic** [crowdsecurity/helm-charts#260]
Consider the following values.yaml

```
# -- Enable AppSec (https://docs.crowdsec.net/docs/next/appsec/intro)
appsec:
  # -- Enable AppSec (by default disabled)
  enabled: true
  # -- podAnnotations for appsec pods
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '6060'
```

Generation fails with message

```
Error: YAML parse error on crowdsec/templates/appsec-deployment.yaml: error converting YAML to JSON: yaml: line 20: mapping values are not allowed in this context
```

Here's the snippet that is rendered

```
# Source: crowdsec/templates/appsec-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-appsec
  labels:
    k8s-app: crowdsec
    type: appsec
    version: v1
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: crowdsec
      type: appsec
  template:
    metadata:
      annotations:
        checksum/appsec-acquis-configmap: d5bf4ff95946e7036bef9f9fff4e2759090223b45e948859e987fbb8950076cd        prometheus.io/port: "6060"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: crowdsec
        type: appsec
        version: v1
```

As you can see, `prometheus.io/port` is located on the same line as checksum for config map. Other deployment.yml files have fixed the issue by not using `{{- toYaml ..`. Instead, they use `{{ toYaml ...` (without the dash). `podLabels` have been handled correctly, by the way.
