### ISSUE TITLE
Intended purpose of extraInitContainers in helm chart or possible indentation bug

### ISSUE THREAD

**Issue by schnurrro** [crowdsecurity/helm-charts#269]
## Description
I want to add an extraInitContainer to the LAPI pod to execute a script found in a configmap. As far as I understood I can use extraInitContainers as described in the [default values.yaml file](https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/values.yaml#L215). 
Further I added the  according yaml section in my values.yaml, but when parsing the chart using helm I encounter a mismatching indentation, my yaml section is added to the bottom of default initContainer "fetch-metabase-config" instead of being an own element in the list of initContainers. 
Is the intended behaviour of the chart to add fields to the default initContainer or might this be an indentation bug?

## Yaml input
Snippet of my values.yaml defining an extraInitContainer mounting a configmap:
```yaml
lapi:
  extraInitContainers:
    - name: init-something
      image: alpine:3.19
      command: ["/bin/sh", "/scripts/init-something.sh"]
      volumeMounts:
        - name: init-something
          mountPath: /scripts
          readOnly: true
  extraVolumes:
    - name: init-something
      configMap:
        name: init-something
        defaultMode: 0755
```

## Expected behavior
I expected that my extraInitContainer will be the second initContainer with a parsed yaml like the following:
```yaml
    spec:
      initContainers:
      - name: fetch-metabase-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'if [ -f /metabase-data/metabase.db/metabase.db.mv.db ]; then echo "Metabase database file already exists, skipping download and unzip"; else wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -nd /metabase-data/; fi']
        volumeMounts:
        - name: crowdsec-db
          mountPath: /metabase-data
          subPath: dashboard
      - command:
        - /bin/sh
        - /scripts/init-something.sh
        image: alpine:3.19
        name: init-something
        volumeMounts:
        - mountPath: /scripts
          name: init-something
          readOnly: true
```

## Actual behavior
The extraInitContainer was inserted under the key volumeMounts of the default initContainer:
```yaml
    spec:
      initContainers:
      - name: fetch-metabase-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'if [ -f /metabase-data/metabase.db/metabase.db.mv.db ]; then echo "Metabase database file already exists, skipping download and unzip"; else wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -nd /metabase-data/; fi']
        volumeMounts:
        - name: crowdsec-db
          mountPath: /metabase-data
          subPath: dashboard
        - command:
          - /bin/sh
          - /scripts/init-something.sh
          image: alpine:3.19
          name: init-something
          volumeMounts:
          - mountPath: /scripts
            name: init-something
            readOnly: true
```

## Steps to Reproduce
Add an extraInitContainer to the values.yaml and proceed with `helm template`.

## Suggested fix
When having a look at the [template](https://github.com/crowdsecurity/helm-charts/blob/00ff47d77c437090605240bd73c4c863d84199e7/charts/crowdsec/templates/lapi-deployment.yaml#L64C15-L64C36) of the deployment for LAPI it's visible that the nindent shows 8 which is the reason why this occurs. 
As seen in the snippet from this file the first element of initContainers is introduced by "- name: fetch-metabase-config" with an indentation of 6 spaces until the -.
For the next element which is coming from extraInitContainers there will be an indentation of 8 spaces (nindent 8) which leads to the inserted yaml being part of the previous list element instead of a new one. 

```yaml
      initContainers:
      {{- if .Values.lapi.dashboard.enabled }}
      - name: fetch-metabase-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'if [ -f /metabase-data/metabase.db/metabase.db.mv.db ]; then echo "Metabase database file already exists, skipping download and unzip"; else wget {{ .Values.lapi.dashboard.assetURL }} && unzip metabase_sqlite.zip -nd /metabase-data/; fi']
        volumeMounts:
        - name: crowdsec-db
          mountPath: /metabase-data
          subPath: dashboard
      {{- end }}
      {{- if .Values.lapi.extraInitContainers }}
      {{- toYaml .Values.lapi.extraInitContainers | nindent 8 }}
      {{- end }}
      {{- end }}
```
When changing `{{- toYaml .Values.lapi.extraInitContainers | nindent 8 }}` to `{{- toYaml .Values.lapi.extraInitContainers | nindent 6 }}` it should be fixed.
