### ISSUE TITLE
Bug with the acquis file when using Traefik.

### ISSUE THREAD

**Issue by SpaceComet** [crowdsecurity/helm-charts#30]
Hi!

I have a small k3s cluster with traefik as an ingress.  

Here is my `crowdsec-values.yaml` file

```yaml
agent:
  # To specify each pod you want to process it logs (pods present in the node)
  acquisition:
    # The namespace where the pod is located
    - namespace: kube-system
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
      program: traefik
  # Those are ENV variables
  env:
  # As it's a test, we don't want to share signals with CrowdSec so disable the Online API.
  - name: DISABLE_ONLINE_API
    value: "true"
  - name: COLLECTIONS
    value: "crowdsecurity/linux crowdsecurity/traefik"
lapi:
  env:
    # As it's a test, we don't want to share signals with CrowdSec, so disable the Online API.
    - name: DISABLE_ONLINE_API
      value: "true"
```
When I install crowdsec on my cluster with:

```bash
$ helm upgrade --install crowdsec crowdsec/crowdsec -f crowdsec-values.yaml -n crowdsec
```

Everything gets installed well but the `crowdsecurity/traefik-logs` parser does not parse the log file from traefik:

```bash
/ # cscli metrics
INFO[24-02-2022 02:30:11 AM] Acquisition Metrics:                         
+--------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
|                                                                   SOURCE                                                                   | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+--------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
| file:/var/log/containers/traefik-84dc64fc99-zpmql_kube-system_traefik-c6117359e65ea7aabedacc6bbc0f502ed55c61f76a1d4559e17e225ca6cb2a1c.log |        835 | -            |            835 | -                      |
+--------------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+----------------+------------------------+
INFO[24-02-2022 02:30:11 AM] Parser Metrics:                              
+----------------------------------------+-------+--------+----------+
|                PARSERS                 | HITS  | PARSED | UNPARSED |
+----------------------------------------+-------+--------+----------+
| child-child-crowdsecurity/traefik-logs | 10855 |   2505 |     8350 |
| child-crowdsecurity/traefik-logs       |  1670 | -      |     1670 |
| crowdsecurity/docker-logs              |   835 |    835 | -        |
| crowdsecurity/traefik-logs             |   835 | -      |      835 |
+----------------------------------------+-------+--------+----------+
```

This is happening because the helm chart that creates the `acquis.yaml` file does this:

```
filenames:
  - /var/log/containers/traefik-*_kube-system_*.log
labels:
  type: docker # <-- Here is the problem
  program: traefik
```
When I manually modify this file to `type: traefik`  then the parser starts working

---

I think we should be able to declare the `labels.type` to avoid this problem

**Comment by he2ss** [comment]
Hi @SpaceComet,

It's because you're running k8s cluster on k3s that uses containerd to run containers and not docker.
So logs are in CRI format and not json.

You just need to change this value `container_runtime: docker` to `container_runtime: containerd`.
As expained in this issue: https://github.com/crowdsecurity/crowdsec/issues/1213#issuecomment-1024442029

**Comment by SpaceComet** [comment]
Hi @he2ss. Yes! this works by making those changes!

Is this documented somewhere?

Here is my conf file in case that helps someone:

```yaml
container_runtime: containerd

agent:
  # To specify each pod you want to process it logs (pods present in the node)
  acquisition:
    # The namespace where the pod is located
    - namespace: kube-system
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
      program: traefik
  # Those are ENV variables
  env:
  # As it's a test, we don't want to share signals with CrowdSec so disable the Online API.
  - name: DISABLE_ONLINE_API
    value: "true"
  # As we are running Traefik, we want to install the Traefik collection
  - name: COLLECTIONS
    value: "crowdsecurity/linux crowdsecurity/traefik"
  - name: PARSERS
    value: "crowdsecurity/cri-logs"
lapi:
  env:
    # As it's a test, we don't want to share signals with CrowdSec, so disable the Online API.
    - name: DISABLE_ONLINE_API
      value: "true"
```
