### ISSUE TITLE
mv: can't rename '/etc/crowdsec/*': No such file or directory

### ISSUE THREAD

**Issue by ybizeul** [crowdsecurity/helm-charts#34]
`lapi` container `CrashLoopBackOff`

I think it's since 1.3.1 release.

```
crowdsec-lapi-c4d9bcd95-tf952     0/1     CrashLoopBackOff   2          48s
❯ k logs -f crowdsec-lapi-c4d9bcd95-tf952
mv: can't rename '/etc/crowdsec/*': No such file or directory
```

In the custom values, I changed image policy pull to Always. Setting it to `IfNotPresent` prevents upgrade of the container, then warning appears in the logs and scenarios won't install because hub is out of sync.

```
image:
  repository: crowdsecurity/crowdsec
  pullPolicy: Always
agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
  env:
    - name: SCENARIOS
      value: "crowdsecurity/http-logs crowdsecurity/http-crawl-non_statics"
    - name: PARSERS
      value: "crowdsecurity/traefik-logs"

lapi:
  dashboard:
    enabled: false
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 150m
      memory: 100Mi
```
