### ISSUE TITLE
Specifying multiple acquisitions results in invalid format of acquis.yaml

### ISSUE THREAD

**Issue by krohrsb** [crowdsecurity/helm-charts#48]
https://github.com/crowdsecurity/helm-charts/blob/7b7ad55c3f86903323c41b70f210ca3d9163c23c/charts/crowdsec/templates/acquis-configmap.yaml#L10

This loops over multiple entries in the helm's acquisitions array, however it does not delimit each config with the `---` notation, resulting in a parsing error when you wish to define more than one acquisition.

Current Result:

```yaml
apiVersion: v1
data:
  acquis.yaml: |-
    filenames:
      - /var/log/containers/traefik-*_my-namespace_*.log
    labels:
      type: containerd
      program: traefik
    filenames:
      - /var/log/containers/foo-*_another-namespace_*.log
    labels:
      type: containerd
      program: my-program
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: crowdsec
  name: acquis-configmap
  namespace: my-namespace
```

Expected:

```yaml
apiVersion: v1
data:
  acquis.yaml: |-
    filenames:
      - /var/log/containers/traefik-*_my-namespace_*.log
    labels:
      type: containerd
      program: traefik
    ---
    filenames:
      - /var/log/containers/foo-*_another-namespace_*.log
    labels:
      type: containerd
      program: my-program
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: crowdsec
  name: acquis-configmap
  namespace: my-namespace
```

Format, for example: https://github.com/crowdsecurity/crowdsec/blob/master/config/acquis.yaml
