### ISSUE TITLE
Chart 0.8.2 - YAML parse error on crowdsec/templates/lapi-deployment.yaml

### ISSUE THREAD

**Issue by ahgraber** [crowdsecurity/helm-charts#76]
When upgrading my chart to `0.8.2`, I get the following error:

```txt
helm upgrade failed: YAML parse error on crowdsec/templates/lapi-deployment.yaml: 
error converting YAML to JSON:
yaml: line 59: mapping values are not allowed in this context
```

the relevant `lapi` section of my `values.yaml`:

```yamlimage:
    repository: crowdsecurity/crowdsec
    tag: "latest"

  lapi:
    env:
      - name: DISABLE_AGENT
        value: "true"
      - name: ENROLL_KEY
        valueFrom:
          secretKeyRef:
            name: crowdsec-secret
            key: ENROLL_KEY
      - name: ENROLL_INSTANCE_NAME
        value: "k8s_cluster"

    dashboard:
      enabled: false
      ingress:
        enabled: false

    resources:
      requests:
        cpu: 150m
        memory: 100M
      limits:
        memory: 100M

    # -- Enable persistent volumes
    persistentVolume:
      # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
      data:
        enabled: true
        accessModes:
          - ReadWriteOnce
        storageClassName: "ceph-fs"
        size: 1Gi
      # -- Persistent volume for config folder. Stores e.g. online api credentials
      config:
        enabled: true
        accessModes:
          - ReadWriteOnce
        storageClassName: "ceph-fs"
        size: 100Mi
```

**Comment by he2ss** [comment]
Hi @ahgraber,

Could you please paste all the values content so we can try to reproduce the error.

**Comment by ahgraber** [comment]
```yaml
# -- for raw logs format: json or cri (docker|containerd)
container_runtime: containerd

image:
  # -- docker image repository name
  repository: crowdsecurity/crowdsec
  # -- pullPolicy
  pullPolicy: IfNotPresent
  # -- docker image tag
  tag: "latest"

# # If you want to specify secrets that will be used for all your crowdsec-agents
# # secrets can be provided be env variables
# secrets:
#   # -- agent username (default is generated randomly)
#   username: ""
#   # -- agent password (default is generated randomly)
#   password: ""

# lapi (local api) will deploy pod with crowdsec lapi and dashboard as deployment
lapi:
  env:
    # by default disable the agent for local API pods
    - name: DISABLE_AGENT
      value: "true"
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-secret
          key: ENROLL_KEY
    - name: ENROLL_INSTANCE_NAME
      value: "k8s_cluster"
    # - name: ENROLL_TAGS
    #   value: "k8s linux test"
    # # If it's a test, we don't want to share signals with CrowdSec so disable the Online API.
    # - name: DISABLE_ONLINE_API
    #   value: "true"
  dashboard:
    # -- Enable Metabase Dashboard (by default disabled)
    enabled: false
    ingress:
      enabled: false

  resources:
    requests:
      cpu: 150m
      memory: 100M
    limits:
      memory: 100M

  # -- Enable persistent volumes
  persistentVolume:
    # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
    data:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: "ceph-fs"
      size: 1Gi
    # -- Persistent volume for config folder. Stores e.g. online api credentials
    config:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: "ceph-fs"
      size: 100Mi

  nodeSelector:
    node-role.kubernetes.io/master: "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"

  # -- Enable service monitoring (exposes "metrics" port "6060" for Prometheus)
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

# agent will deploy pod on every node as daemonSet to read wanted pods logs
agent:
  acquisition:
    # -- Specify each pod you want to process it logs (namespace, podName and program)
    - namespace: networking
      podName: traefik-*
      program: traefik
    # - namespace: security
    #   podName: keycloak-postgresql-*
    #   program: pgsql
  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 150m
      memory: 100Mi
  # -- Enable persistent volumes
  persistentVolume:
    # -- Persistent volume for config folder. Stores local config (parsers, scenarios etc.)
    config:
      enabled: true
      accessModes:
        - ReadWriteMany
      storageClassName: "ceph-fs"
      size: 100Mi
  # -- environment variables from crowdsecurity/crowdsec docker image
  env:
    # As we are running Traefik, we want to install the Traefik collection
    - name: COLLECTIONS
      value: "crowdsecurity/linux"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    - name: COLLECTIONS
      value: "crowdsecurity/base-http-scenarios"
    - name: COLLECTIONS
      value: "crowdsecurity/http-cve"
    - name: COLLECTIONS
      value: "crowdsecurity/mariadb"
    - name: COLLECTIONS
      value: "crowdsecurity/pgsql"
    - name: COLLECTIONS
      value: "crowdsecurity/sshd"

    - name: PARSERS
      value: "crowdsecurity/cri-logs"

    - name: TZ
      value: "${TIMEZONE}"
    - name: DISABLE_ONLINE_API
      value: "false"
    # - name: LEVEL_TRACE
    #   value: "false"
    # - name: LEVEL_DEBUG
    #   value: "false"
    # - name: LEVEL_INFO
    #   value: "false"

  # -- tolerations for agent
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"

  # -- Enable service monitoring (exposes "metrics" port "6060" for Prometheus)
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```

the deployment uses fluxcd for gitops and the repo is public, you can see everything attached to the deployment [here](https://github.com/ahgraber/homelab-gitops-k3s/tree/main/cluster/apps/security/crowdsec)
