### ISSUE TITLE
Update to 1.4.4 crowdsec final and are we able to specify the version?

### ISSUE THREAD

**Issue by mannp** [crowdsecurity/helm-charts#80]
Updated values.yaml as follows, but it appears to be ignored?

```
  values:
    container_runtime: containerd
    image:
      repository: crowdsecurity/crowdsec
      tag: v1.4.4
```

`deployed             crowdsec-0.8.2                    v1.4.4-rc1`

Thanks
