### ISSUE TITLE
[feat] Support additional custom acquisitions  

### ISSUE THREAD

**Issue by krohrsb** [crowdsecurity/helm-charts#88]
Today, you can only configure container-based acquisitions through the `acquisition:` array, specifying namespace/podName/program.

I believe it would be beneficial to support specifying raw acquisition array items as well, so that we can monitor things in the already-mounted `/var/log/` directory, that are *not* container based.

For example, if I wanted to leverage the fastly example:

```
---
filename: /var/log/crowdsec_fastly.log
labels:
  type: syslog
  external_format: fastly
```

I have no way of adding this (that I know of) using this helm chart today.
