### ISSUE TITLE
How to manage bouncers?

### ISSUE THREAD

**Issue by wexder** [crowdsecurity/helm-charts#95]
Is there a way how to manage the bouncers from the helm chart ? So far I'm not seeing any way how to mange them in declarative way, which would make deploying and managing crowdsec in infrastructure as code environments hard.
Is there something I'm missing ? 
Thanks

**Comment by LaurenceJJones** [comment]
We support adding bouncers via the environment of the LAPI

https://hub.docker.com/r/crowdsecurity/crowdsec

```
BOUNCER_KEY_<name>: <api_key>

## for example
BOUNCER_KEY_nginx: "pZo$#K!CcC!CBgRy2zTmRmt#3Erz*efSL6s!kj5V"
```

**Comment by worldsayshi** [comment]
I don't really understand this instruction but I eventually figured it out.

Run this in a crowdsec lapi pod:
cscli bouncers add traefik-ingress
And use that key as the bouncer.crowdsec_bouncer_api_key

However, I didn't use the bouncer helm chart from this repo. Instead I changed the traefik helm chart values to add maxlerebourg/crowdsec-bouncer-traefik-plugin. This approach had quite a few pitfalls so this bouncer helm chart might be easier. But I assume the end effect is the same.

Here's my work in progress bouncer set up if anyone needs it:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: monorepo-private
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    retry:
      limit: 10
    automated:
      prune: true
      selfHeal: true
  source:
    path: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart.git
    targetRevision: HEAD
    helm:
      valuesObject:
        deployment:
          initContainers:
            - name: volume-permissions
              image: busybox:latest
              command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
              volumeMounts:
              - mountPath: /data
                name: data
          additionalVolumes:
            - name: plugins
        additionalVolumeMounts:
          - name: plugins
            mountPath: /plugins-storage

        experimental:
          plugins:
            bouncer:
              moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
              version: v1.1.16
        additionalArguments:
          - --providers.kubernetescrd.allowCrossNamespace=true
        persistence:
          enabled: true
          storageClass: local-path
        certResolvers:
          letsencrypt:
            dnsChallenge:
              provider: hetzner
            storage: /data/acme.json
            caserver: https://acme-staging-v02.api.letsencrypt.org/directory

        logs:
          general:
            level: DEBUG
          access:
            enabled: true
            fields:
              headers: 
                defaultmode: keep
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: argocd
spec:
    plugin:
        bouncer:
            CrowdsecLapiKey: --- KEY HERE ---
            Enabled: "true"
            logLevel: DEBUG
            crowdsecMode: live
            crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
            crowdsecLapiScheme: http
```
